//
//  BirdBank.swift
//  WordOfTheBird
//
//  Created by Banana Viking on 8/16/18.
//  Copyright © 2018 Banana Viking. All rights reserved.
//

import UIKit
import AVFoundation

class BirdBank {
    let birds = [
        Bird(name: "American Goldfinch",
             imageSmall: "americanGoldfinchImageSmall",
             imageLarge: "americanGoldfinchImageLarge",
             calls: ["americanGoldfinchCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/American_goldfinch"),
        Bird(name: "American Kestrel",
             imageSmall: "americanKestrelImageSmall",
             imageLarge: "americanKestrelImageLarge",
             calls: ["americanKestrelCall1", "americanKestrelCall2"],
             wikiLink: "https://en.wikipedia.org/wiki/American_kestrel"),
        Bird(name: "Bald Eagle",
             imageSmall: "baldEagleImageSmall",
             imageLarge: "baldEagleImageLarge",
             calls: ["baldEagleCall1", "baldEagleCall2", "baldEagleCall3"],
             wikiLink: "https://en.wikipedia.org/wiki/Bald_eagle"),
        Bird(name: "Barred Owl",
             imageSmall: "barredOwlImageSmall",
             imageLarge: "barredOwlImageLarge",
             calls: ["barredOwlCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Barred_owl"),
        Bird(name: "Black-capped Chickadee",
             imageSmall: "blackCappedChickadeeImageSmall",
             imageLarge: "blackCappedChickadeeImageLarge",
             calls: ["blackCappedChickadeeCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Black-capped_chickadee"),
        Bird(name: "Blue Jay",
             imageSmall: "blueJayImageSmall",
             imageLarge: "blueJayImageLarge",
             calls: ["blueJayCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Blue_jay"),
        Bird(name: "Downy Woodpecker",
             imageSmall: "downyWoodpeckerImageSmall",
             imageLarge: "downyWoodpeckerImageLarge",
             calls: ["downyWoodpeckerCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Downy_woodpecker"),
        Bird(name: "Great Horned Owl",
             imageSmall: "greatHornedOwlImageSmall",
             imageLarge: "greatHornedOwlImageLarge",
             calls: ["greatHornedOwlCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Great_horned_owl"),
        Bird(name: "Hairy Woodpecker",
             imageSmall: "hairyWoodpeckerImageSmall",
             imageLarge: "hairyWoodpeckerImageLarge",
             calls: ["hairyWoodpeckerCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Hairy_woodpecker"),
        Bird(name: "House Finch",
             imageSmall: "houseFinchImageSmall",
             imageLarge: "houseFinchImageLarge",
             calls: ["houseFinchCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/House_finch"),
        Bird(name: "Northern Cardinal",
             imageSmall: "cardinalImageSmall",
             imageLarge: "cardinalImageLarge",
             calls: ["northernCardinalCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Northern_cardinal"),
        Bird(name: "Northern Flicker",
             imageSmall: "northernFlickerImageSmall",
             imageLarge: "northernFlickerImageLarge",
             calls: ["northernFlickerCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Northern_flicker"),
        Bird(name: "Peregrine Falcon",
             imageSmall: "peregrineFalconImageSmall",
             imageLarge: "peregrineFalconImageLarge",
             calls: ["peregrineFalconCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Peregrine_falcon"),
        Bird(name: "Pileated Woodpecker",
             imageSmall: "pileatedWoodpeckerImageSmall",
             imageLarge: "pileatedWoodpeckerImageLarge",
             calls: ["pileatedWoodpeckerCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Pileated_woodpecker"),
        Bird(name: "Red-bellied Woodpecker",
             imageSmall: "redBelliedWoodpeckerImageSmall",
             imageLarge: "redBelliedWoodpeckerImageLarge",
             calls: ["redBelliedWoodpeckerCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Red-bellied_woodpecker"),
        Bird(name: "Red-headed Woodpecker",
             imageSmall: "redHeadedWoodpeckerImageSmall",
             imageLarge: "redHeadedWoodpeckerImageLarge",
             calls: ["redHeadedWoodpeckerCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Red-headed_woodpecker"),
        Bird(name: "Red-tailed Hawk",
             imageSmall: "redTailedHawkImageSmall",
             imageLarge: "redTailedHawkImageLarge",
             calls: ["redTailedHawkCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Red-tailed_hawk"),
        Bird(name: "Tufted Titmouse",
             imageSmall: "tuftedTitmouseImageSmall",
             imageLarge: "tuftedTitmouseImageLarge",
             calls: ["tuftedTitmouseCall1"],
             wikiLink: "https://en.wikipedia.org/wiki/Tufted_titmouse")
    ]
}
