//
//  BirdBank.swift
//  WordOfTheBird
//
//  Created by Banana Viking on 8/16/18.
//  Copyright © 2018 Banana Viking. All rights reserved.
//

import UIKit
import AVFoundation

class BirdBank {
    let birds = [
        Bird(name: "American Goldfinch",
             imageSmall: "americanGoldfinchImageSmall",
             imageLarge: "americanGoldfinchImageLarge",
             calls: ["americanGoldfinchCall1", "americanGoldfinchCall2"],
             infoLink: "https://www.allaboutbirds.org/guide/American_Goldfinch/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/American_Goldfinch/maps-range"),
        Bird(name: "American Kestrel",
             imageSmall: "americanKestrelImageSmall",
             imageLarge: "americanKestrelImageLarge",
             calls: ["americanKestrelCall1", "americanKestrelCall2"],
             infoLink: "https://www.allaboutbirds.org/guide/American_Kestrel/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/American_Kestrel/maps-range"),
        Bird(name: "Bald Eagle",
             imageSmall: "baldEagleImageSmall",
             imageLarge: "baldEagleImageLarge",
             calls: ["baldEagleCall1", "baldEagleCall2", "baldEagleCall3"],
             infoLink: "https://www.allaboutbirds.org/guide/Bald_Eagle/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Bald_Eagle/maps-range"),
        Bird(name: "Barred Owl",
             imageSmall: "barredOwlImageSmall",
             imageLarge: "barredOwlImageLarge",
             calls: ["barredOwlCall1"],
             infoLink: "https://www.allaboutbirds.org/guide/Barred_Owl/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Barred_Owl/maps-range"),
        Bird(name: "Black-capped Chickadee",
             imageSmall: "blackCappedChickadeeImageSmall",
             imageLarge: "blackCappedChickadeeImageLarge",
             calls: ["blackCappedChickadeeCall1", "blackCappedChickadeeCall2"],
             infoLink: "https://www.allaboutbirds.org/guide/Black-capped_Chickadee/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Black-capped_Chickadee/maps-range"),
        Bird(name: "Blue Jay",
             imageSmall: "blueJayImageSmall",
             imageLarge: "blueJayImageLarge",
             calls: ["blueJayCall1", "blueJayCall2"],
             infoLink: "https://www.allaboutbirds.org/guide/Blue_Jay/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Blue_Jay/maps-range"),
        Bird(name: "Downy Woodpecker",
             imageSmall: "downyWoodpeckerImageSmall",
             imageLarge: "downyWoodpeckerImageLarge",
             calls: ["downyWoodpeckerCall1"],
             infoLink: "https://www.allaboutbirds.org/guide/Downy_Woodpecker/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Downy_Woodpecker/maps-range"),
        Bird(name: "Great Horned Owl",
             imageSmall: "greatHornedOwlImageSmall",
             imageLarge: "greatHornedOwlImageLarge",
             calls: ["greatHornedOwlCall1"],
             infoLink: "https://www.allaboutbirds.org/guide/Great_Horned_Owl/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Great_Horned_Owl/maps-range"),
        Bird(name: "Hairy Woodpecker",
             imageSmall: "hairyWoodpeckerImageSmall",
             imageLarge: "hairyWoodpeckerImageLarge",
             calls: ["hairyWoodpeckerCall1"],
             infoLink: "https://www.allaboutbirds.org/guide/Hairy_Woodpecker/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Hairy_Woodpecker/maps-range"),
        Bird(name: "House Finch",
             imageSmall: "houseFinchImageSmall",
             imageLarge: "houseFinchImageLarge",
             calls: ["houseFinchCall1", "houseFinchCall2", "houseFinchCall3"],
             infoLink: "https://www.allaboutbirds.org/guide/House_Finch/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/House_Finch/maps-range"),
        Bird(name: "Northern Cardinal",
             imageSmall: "cardinalImageSmall",
             imageLarge: "cardinalImageLarge",
             calls: ["northernCardinalCall1", "northernCardinalCall2"],
             infoLink: "https://www.allaboutbirds.org/guide/Northern_Cardinal/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Northern_Cardinal/maps-range"),
        Bird(name: "Northern Flicker",
             imageSmall: "northernFlickerImageSmall",
             imageLarge: "northernFlickerImageLarge",
             calls: ["northernFlickerCall1", "northernFlickerCall2"],
             infoLink: "https://www.allaboutbirds.org/guide/Northern_Flicker/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Northern_Flicker/maps-range"),
        Bird(name: "Peregrine Falcon",
             imageSmall: "peregrineFalconImageSmall",
             imageLarge: "peregrineFalconImageLarge",
             calls: ["peregrineFalconCall1", "peregrineFalconCall2"],
             infoLink: "https://www.allaboutbirds.org/guide/Peregrine_Falcon/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Peregrine_Falcon/maps-range"),
        Bird(name: "Pileated Woodpecker",
             imageSmall: "pileatedWoodpeckerImageSmall",
             imageLarge: "pileatedWoodpeckerImageLarge",
             calls: ["pileatedWoodpeckerCall1"],
             infoLink: "https://www.allaboutbirds.org/guide/Pileated_Woodpecker/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Pileated_Woodpecker/maps-range"),
        Bird(name: "Red-bellied Woodpecker",
             imageSmall: "redBelliedWoodpeckerImageSmall",
             imageLarge: "redBelliedWoodpeckerImageLarge",
             calls: ["redBelliedWoodpeckerCall1"],
             infoLink: "https://www.allaboutbirds.org/guide/Red-bellied_Woodpecker/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Red-bellied_Woodpecker/maps-range"),
        Bird(name: "Red-headed Woodpecker",
             imageSmall: "redHeadedWoodpeckerImageSmall",
             imageLarge: "redHeadedWoodpeckerImageLarge",
             calls: ["redHeadedWoodpeckerCall1"],
             infoLink: "https://www.allaboutbirds.org/guide/Red-headed_Woodpecker/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Red-headed_Woodpecker/maps-range"),
        Bird(name: "Red-tailed Hawk",
             imageSmall: "redTailedHawkImageSmall",
             imageLarge: "redTailedHawkImageLarge",
             calls: ["redTailedHawkCall1"],
             infoLink: "https://www.allaboutbirds.org/guide/Red-tailed_Hawk/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Red-tailed_Hawk/maps-range"),
        Bird(name: "Tufted Titmouse",
             imageSmall: "tuftedTitmouseImageSmall",
             imageLarge: "tuftedTitmouseImageLarge",
             calls: ["tuftedTitmouseCall1"],
             infoLink: "https://www.allaboutbirds.org/guide/Tufted_Titmouse/lifehistory",
             mapLink: "https://www.allaboutbirds.org/guide/Tufted_Titmouse/maps-range")
    ]
}
